[package]
name = "mistd"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
tokio = { version = "1.46.1", features = ["macros", "rt-multi-thread"] }
wasmtime = "34.0.2"
wasmtime-wasi = "34.0.2"
