[package]
name = "mistctr"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
config = { path = "../config" }
wasmtime = "34.0.2"
wasmtime-wasi = "34.0.2"
dashmap = "6.1.0"
sled = "0.34.7"
serde_json = "1.0.141"
tokio = "1.46.1"
